inherit = "config/common/pvt_se_train_si_sdr_scp.toml"

[meta]
save_dir = "experiments"
use_amp = false

[model]
path = "src.model.pvt_se_model.Model"
[model.args]
pe_depth = 0
#look_ahead = 2

[model.backbone]
path = "src.model.module.pvt.PyramidVisionTransformer"
[model.backbone.args]
spec_size = [256, 128]
patch_size = [[8,2], [2,2], [2,1], [1,1]]
embed_dims = [64, 128, 320, 512]
num_heads = [1, 2, 5, 8]
mlp_ratios = [8, 8, 4, 4]
qkv_bias = true
depths = [2, 2, 2, 2]
sr_ratios = [8, 4, 2, 1]
att_vis = false
[model.backbone.args.conv_cfg]
in_channels = 2
out_channels = 16
kernel_size = [3, 5]
stride = 1
padding = [1, 2]
activate_function = "PReLU"
with_norm = true


[model.head]
path = "src.model.module.pvt_decoder.DePyramidVisionTransformer"
[model.head.args]
feature_size = [8, 32]
patch_size = [[1,1], [2,1], [2,2], [8,2]]
embed_dims = [512, 320, 128, 64]
num_heads = [4, 2, 1]
mlp_ratios = [4, 8, 8]
qkv_bias = true
depths = [2, 2, 2]
sr_ratios = [2, 4, 8]
att_vis = false

[model.head.args.conv_cfg]
in_channels = 32
out_channels = 2
kernel_size = [3, 5]
stride = 1
padding = [1, 2]
activate_function = false
final_amplification = 1
with_norm = false

[train_dataset]
path = "dataset.dataset_from_scp.Dataset"
[train_dataset.args]
path = "/home/administrator/Data/DNS-Challenge_142h_5ep/"

[train_dataset.sampler]
shuffle = true

[train_dataset.dataloader]
batch_size = 36
num_workers = 4

[validation_dataset]
path = "dataset.DNS_INTERSPEECH_validation.Dataset"

[trainer]
path = "trainer.pvt_se_trainer_si_sdr_scp.Trainer"
[trainer.train]
epochs = 12
save_checkpoint_interval = 1
[trainer.validation]
validation_interval = 1
[trainer.visualization]
n_samples = 20
num_workers = 6
metrics = ["WB_PESQ", "NB_PESQ", "STOI", "SI_SDR"]
