[acoustic]
sr = 16000
n_fft = 510
win_length = 510
hop_length = 255
center = true
power = 0.3


[inferencer]
path = "inferencer.DNS_INTERSPEECH_framed.Inferencer"
type =  "pvt_se_crm_mask"
[inferencer.args]
compress_mask = false
sub_sample_length = 2.0399375
sr = 16000


[dataset]
path = "dataset.DNS_INTERSPEECH_inference.Dataset"
[dataset.args]
noisy_dataset = ["/home/administrator/Data/DNS-Challenge/datasets/test_set/synthetic/no_reverb/audio/noisy",
                 "/home/administrator/Data/DNS-Challenge/datasets/test_set/synthetic/with_reverb/audio/noisy"]
limit = false
offset = 0
sr = 16000


[model]
path = "src.model.pvt_se_model.Model"
[model.args]
pe_depth = 10
#look_ahead = 2

[model.backbone]
path = "src.model.module.pvt_v2.PyramidVisionTransformerV2"
[model.backbone.args]
spec_size = [256, 128]
in_chans = 16
patch_size = [[7,7], [3,3], [3,3], [3,3]]
embed_dims = [32, 64, 160, 256]
num_heads = [1, 2, 5, 8]
mlp_ratios = [8, 8, 4, 4]
qkv_bias = true
depths = [2, 2, 2, 2]
sr_ratios = [8, 4, 2, 1]
drop_rate = 0.0
drop_path_rate = 0.1
[model.backbone.args.conv_cfg]
in_channels = 12
out_channels = 16
kernel_size = [3, 5]
stride = 1
padding = [1, 2]
activate_function = "PReLU"
with_norm = true


[model.head]
path = "src.model.module.pvt_v2_decoder.DePyramidVisionTransformerV2"
[model.head.args]
spec_size = [8, 4]
patch_size = [[3,3], [3,3], [3,3], [7,7]]
embed_dims = [256, 160, 64, 32]
num_heads = [8, 4, 2, 1]
mlp_ratios = [4, 4, 8, 8]
qkv_bias = true
depths = [2, 2, 2, 2]
sr_ratios = [1, 2, 4, 8]
drop_rate = 0.0
drop_path_rate = 0.1
[model.head.args.conv_cfg]
in_channels = 32
out_channels = 2
kernel_size = [3, 5]
stride = 1
padding = [1, 2]
activate_function = false
final_amplification = 1
with_norm = false
