inherit = "config/common/pvt_se_si_sdr_inference.toml"

[inferencer.args]
att_vis = true

[dataset]
path = "dataset.DNS_INTERSPEECH_inference.Dataset"
[dataset.args]
noisy_dataset = ["/home/administrator/Data/DNS-Challenge/datasets/test_set/synthetic/with_reverb/audio/noisy"]
#noisy_dataset = ["/home/administrator/Data/test_noise"]
limit = false
offset = 0
sr = 16000
